// M0 主机侧测试入口（M0-A / M0-B1 / M0-B2 / M0-C）。
#include <cstdio>

#include "test_util.h"

void runByteOrderTests();
void runDecoderTimeoutTests();
void runAckReqTests();
void runCrcTests();
void runPacketTests();
void runEncoderTests();
void runDecoderTests();
void runFrameAssemblerTests();
void runPipelineTests();
void runFramePipelineTests();
void runProtocolEndpointTests();
void runEndpointConcurrencyTests();
void runAckConcurrencyTests();
void runEndpointRaceTests();
void runEndpointLifecycleTests();
void runEndpointStressTests();
void runDeferredControlTests();
void runCapabilitiesTests();
void runPhysicalPreviewTests();
void runWifiProvisioningTests();
void runOledPreviewTests();
void runStreamingEncoderTests();
void runInputTests();
void runLvglAdapterTests();
void runRuntimeStatsTests();
void runRemoteDisplayTests();
void runDisplayRouterTests();
void runDisplayUiStateTests();
void runLogicalSceneTests();
void runPhysicalStatusTests();
void runPhysicalCapabilitySnapshotTests();
void runSplitStateTests();
void runTransportManagerTests();
void runTransportSinkTests();
void runTransportPipelineTests();
void runBoundedQueueTests();
void runLifecycleTests();
void runReconnectPolicyTests();
void runOledTests();
void runOledStatusTests();
void runPhysicalRendererTests();
void runSceneRendererTests();
void runPhysicalPreviewStateTests();
void runWifiWizardStateTests();

int main() {
    // 无缓冲：测试名实时输出，便于定位挂起/超时位置（与 pc 测试工具一致）。
    std::setvbuf(stdout, nullptr, _IONBF, 0);
    std::printf("== ESPView shared/protocol host tests ==\n");
    std::printf("[byte_order]\n");
    runByteOrderTests();
    std::printf("[decoder_timeout]\n");
    runDecoderTimeoutTests();
    std::printf("[ack_req]\n");
    runAckReqTests();
    std::printf("[crc]\n");
    runCrcTests();
    std::printf("[packet]\n");
    runPacketTests();
    std::printf("[encoder]\n");
    runEncoderTests();
    std::printf("[decoder]\n");
    runDecoderTests();
    std::printf("[frame_assembler]\n");
    runFrameAssemblerTests();
    std::printf("[pipeline]\n");
    runPipelineTests();
    std::printf("[frame_pipeline]\n");
    runFramePipelineTests();
    std::printf("[protocol_endpoint]\n");
    runProtocolEndpointTests();
    std::printf("[endpoint_concurrency]\n");
    runEndpointConcurrencyTests();
    std::printf("[ack_concurrency]\n");
    runAckConcurrencyTests();
    std::printf("[endpoint_race]\n");
    runEndpointRaceTests();
    std::printf("[endpoint_lifecycle]\n");
    runEndpointLifecycleTests();
    std::printf("[endpoint_stress]\n");
    runEndpointStressTests();
    std::printf("[deferred_control]\n");
    runDeferredControlTests();
    std::printf("[capabilities]\n");
    runCapabilitiesTests();
    std::printf("[physical_preview]\n");
    runPhysicalPreviewTests();
    std::printf("[wifi_provisioning]\n");
    runWifiProvisioningTests();
    std::printf("[oled_preview]\n");
    runOledPreviewTests();
    std::printf("[streaming_encoder]\n");
    runStreamingEncoderTests();
    std::printf("[input]\n");
    runInputTests();
    runLvglAdapterTests();
    std::printf("[runtime_stats]\n");
    runRuntimeStatsTests();
    std::printf("[remote_display]\n");
    runRemoteDisplayTests();
    std::printf("[display_router]\n");
    runDisplayRouterTests();
    std::printf("[display_ui_state]\n");
    runDisplayUiStateTests();
    std::printf("[logical_scene]\n");
    runLogicalSceneTests();
    std::printf("[physical_status]\n");
    runPhysicalStatusTests();
    runPhysicalCapabilitySnapshotTests();
    std::printf("[split_state]\n");
    runSplitStateTests();
    std::printf("[transport_manager]\n");
    runTransportManagerTests();
    std::printf("[transport_sink]\n");
    runTransportSinkTests();
    std::printf("[transport_pipeline]\n");
    runTransportPipelineTests();
    std::printf("[bounded_queue]\n");
    runBoundedQueueTests();
    std::printf("[lifecycle_failure_injection]\n");
    runLifecycleTests();
    std::printf("[wifi_reconnect_policy]\n");
    runReconnectPolicyTests();
    std::printf("[oled]\n");
    runOledTests();
    std::printf("[oled_status]\n");
    runOledStatusTests();
    std::printf("[physical_renderer]\n");
    runPhysicalRendererTests();
    std::printf("[scene_renderer]\n");
    runSceneRendererTests();
    std::printf("[physical_preview_state]\n");
    runPhysicalPreviewStateTests();
    std::printf("[wifi_wizard_state]\n");
    runWifiWizardStateTests();
    std::printf("----\nchecks: %d, failures: %d\n",
                espview::proto::test::gChecks.load(),
                espview::proto::test::gFailures.load());
    return espview::proto::test::gFailures.load() == 0 ? 0 : 1;
}
